do { ...
}
while (true);
while (true) { ...
}
for (let i = 0; i < 50; i++) { ...
}
for (let value of array) { ...
}
for (let key in array) { ...
}
// Loops are quite similar to those in C, and variables are loosely typed like they are in Python, with var as the keyword to declare them